from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('preinscription/', views.preinscription, name='preinscription'),
    path('admin/preinscriptions/', views.liste_preinscriptions, name='liste_preinscriptions'),
    path('admin/preinscriptions/<int:preinscription_id>/valider/', views.valider_preinscription, name='valider_preinscription'),
    path('admin/validation-preinscriptions/', views.validation_preinscriptions, name='validation_preinscriptions'),
    path('admin/gestion-matieres/', views.gestion_matieres, name='gestion_matieres'),
    path('admin/gestion-cours/', views.gestion_cours, name='gestion_cours'),
    path('admin/gestion-examens/', views.gestion_examens, name='gestion_examens'),
    path('admin/gestion-classes/', views.gestion_classes, name='gestion_classes'),
    path('admin/gestion-frais/', views.gestion_frais, name='gestion_frais'),
    path('admin/gestion-enseignants/', views.gestion_enseignants, name='gestion_enseignants'),
    path('admin/gestion-eleves/', views.gestion_eleves, name='gestion_eleves'),
    path('admin/gestion-parents/', views.gestion_parents, name='gestion_parents'),
    path('admin/gestion-administrateurs/', views.gestion_administrateurs, name='gestion_administrateurs'),
    path('admin/factures/', views.gestion_factures, name='gestion_factures'),
    path('admin/rapport-financier/', views.rapport_financier, name='rapport_financier'),
    path('admin/paiements/', views.gestion_paiements, name='gestion_paiements'),
    path('admin/preinscriptions-validees/', views.preinscriptions_validees, name='preinscriptions_validees'),
    path('mes-paiements/', views.mes_paiements, name='mes_paiements'),
    path('mes-cours/', views.mes_cours, name='mes_cours'),
    path('saisie-notes/', views.saisir_notes, name='saisie_notes'),
    path('mes-notes/', views.mes_notes, name='mes_notes'),
    path('mes-bulletins/', views.mes_bulletins, name='mes_bulletins'),
    path('admin/generer-bulletins/', views.generer_bulletins, name='generer_bulletins'),
    path('emploi-du-temps/', views.emploi_du_temps, name='emploi_du_temps'),
    path('conversations/', views.conversations, name='conversations'),
    path('conversations/<int:conversation_id>/', views.conversation_detail, name='conversation_detail'),
    path('nouvelle-conversation/', views.nouvelle_conversation, name='nouvelle_conversation'),
    
    # Nouvelles URLs pour notifications, horaires, emplois de temps et sauvegarde
    path('admin/notifications/', views.gestion_notifications, name='gestion_notifications'),
    path('mes-notifications/', views.mes_notifications, name='mes_notifications'),
    path('admin/horaires/', views.gestion_horaires, name='gestion_horaires'),
    path('horaires/', views.voir_horaires, name='voir_horaires'),
    path('emploi-du-temps-avance/', views.emploi_du_temps_avance, name='emploi_du_temps_avance'),
    path('admin/sauvegarde/', views.gestion_sauvegarde, name='gestion_sauvegarde'),
]
